version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      SYMFONY_VERSION:

  caddy:
    build:
      context: .
      target: symfony_caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: postgres:13.0 # set version to 9 if you encounter problems.
    volumes:
      - postgres-vol2:/var/log/postgresql
      - postgres-vol2:/var/lib/postgresql/data:z
      - ./les_des_ranges.sql:/docker-entrypoint-initdb.d/les_des_ranges.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=les_des_ranges

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@local.int
      PGADMIN_DEFAULT_PASSWORD: admin
      PG_DATABASE: les_des_ranges
      PG_USER: postgres
      PG_PASSWORD: admin
    volumes:
      - ./docker/pgadmin:/root/.pgadmin
    ports:
      - 8081:80

volumes:
  caddy_data:
  caddy_config:
  postgres-vol2:
